// FILE: src/components/marketing/PrivacyPage/PrivacyPage.js
import React from "react";
import MarketingNavbar from "../MarketingNavbar/MarketingNavbar";
import MarketingFooter from "../MarketingFooter/MarketingFooter";

export default function PrivacyPage() {
  const lastUpdatedISO = new Date().toISOString();
  const lastUpdated = new Date(lastUpdatedISO).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const sections = [
    { id: "scope", title: "1. Scope" },
    { id: "info-we-collect", title: "2. Information We Collect" },
    { id: "how-we-use", title: "3. How We Use Information" },
    { id: "legal-bases", title: "4. Legal Bases (where applicable)" },
    { id: "sharing", title: "5. Sharing & Disclosure" },
    { id: "security", title: "6. Security" },
    { id: "retention", title: "7. Data Retention" },
    { id: "your-rights", title: "8. Your Rights & Choices" },
    { id: "cookies", title: "9. Cookies & Similar Technologies" },
    { id: "third-parties", title: "10. Third‑Party Services" },
    { id: "children", title: "11. Children’s Privacy" },
    { id: "international", title: "12. International Transfers" },
    { id: "changes", title: "13. Changes to This Policy" },
    { id: "contact", title: "14. Contact Us" },
  ];

  return (
    <div className="d-flex flex-column min-vh-100 bg-body text-body">
      <MarketingNavbar />

      <main className="container py-5">
        {/* Header */}
        <header className="mb-4" id="top">
          <p className="text-uppercase text-muted mb-2 small">Legal</p>
          <h1 className="h3 fw-bold mb-2">Privacy Policy</h1>
          <p className="text-muted mb-0">
            Last updated: <time dateTime={lastUpdatedISO}>{lastUpdated}</time>
          </p>
          <p className="mt-3 mb-0 small text-warning">
            Public beta: Pocket Penny is available at{" "}
            <a
              className="link-primary"
              href="https://pocketpenny.tekimart.com/"
              target="_blank"
              rel="noreferrer"
            >
              pocketpenny.tekimart.com
            </a>
            . Features may evolve and occasional interruptions may occur.
          </p>
        </header>

        <div className="row g-4">
          <div className="col-12 col-lg-8">
            <div className="card border-0 shadow-sm">
              <div className="card-body p-4 p-lg-5">
                {/* TOC */}
                <nav aria-label="Table of contents" className="mb-4">
                  <ul className="list-unstyled mb-0">
                    {sections.map((s) => (
                      <li key={s.id} className="mb-1">
                        <a className="link-primary text-decoration-none" href={`#${s.id}`}>
                          {s.title}
                        </a>
                      </li>
                    ))}
                  </ul>
                </nav>

                {/* Sections */}
                <section id="scope" className="pt-2 mt-2">
                  <h2 className="h5 fw-semibold mb-3">1. Scope</h2>
                  <p>
                    This Privacy Policy explains how Pocket Penny (“we”, “us”, “our”) collects, uses,
                    and shares information when you use our websites and applications (the “Service”).
                    It applies to information you provide directly and information generated by your
                    use of the Service.
                  </p>
                </section>

                <section id="info-we-collect" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">2. Information We Collect</h2>
                  <ul className="mb-2">
                    <li>
                      <strong>Account & authentication:</strong> name, email, profile photo/ID from
                      your sign‑in provider, authentication identifiers, session metadata.
                    </li>
                    <li>
                      <strong>App data you import:</strong> transaction files (e.g., CSV/JSON),
                      categories/tags, budgets, notes. We only store what you choose to upload.
                    </li>
                    <li>
                      <strong>Usage & device:</strong> pages/features used, performance metrics,
                      device/browser information, diagnostics and crash logs.
                    </li>
                  </ul>
                  <p className="small text-muted mb-0">
                    We do not connect to your financial institutions automatically. Imported data is
                    under your control—you can delete it at any time.
                  </p>
                </section>

                <section id="how-we-use" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">3. How We Use Information</h2>
                  <ul className="mb-0">
                    <li>Provide and personalize core features (insights, budgets, forecasting).</li>
                    <li>Process imports and generate analytics you request.</li>
                    <li>Maintain security, prevent abuse, and troubleshoot.</li>
                    <li>Communicate product updates and important notices.</li>
                    <li>Comply with applicable laws and enforce terms.</li>
                  </ul>
                </section>

                <section id="legal-bases" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">4. Legal Bases (where applicable)</h2>
                  <p className="mb-0">
                    Depending on your region, we may process data under one or more legal bases:
                    your consent; performance of a contract (providing the Service); legitimate
                    interests (e.g., security, improving features); and compliance with legal
                    obligations.
                  </p>
                </section>

                <section id="sharing" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">5. Sharing & Disclosure</h2>
                  <ul className="mb-2">
                    <li>
                      <strong>Service providers:</strong> vendors that host, store, or process data
                      for us under contract and instructions.
                    </li>
                    <li>
                      <strong>With your direction:</strong> collaboration or export features you
                      choose to use.
                    </li>
                    <li>
                      <strong>Legal & safety:</strong> when required by law or to protect rights,
                      security, and integrity.
                    </li>
                    <li>
                      <strong>Business transfers:</strong> in a merger, acquisition, or asset sale,
                      subject to continued protections.
                    </li>
                  </ul>
                  <p className="small text-muted mb-0">We do not sell your personal information.</p>
                </section>

                <section id="security" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">6. Security</h2>
                  <p>
                    We implement measures appropriate to the risk, including encryption in transit,
                    access controls, backups, and monitoring. No method of transmission or storage is
                    completely secure; we work to continuously improve our safeguards.
                  </p>
                </section>

                <section id="retention" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">7. Data Retention</h2>
                  <p>
                    We retain information for as long as needed to provide the Service, comply with
                    legal obligations, resolve disputes, and enforce agreements. You can delete your
                    imported datasets at any time from within the app.
                  </p>
                </section>

                <section id="your-rights" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">8. Your Rights & Choices</h2>
                  <ul className="mb-2">
                    <li>Access, correct, or delete your personal information.</li>
                    <li>Download or export your data.</li>
                    <li>Object to or restrict certain processing.</li>
                    <li>Opt‑out of non‑essential communications.</li>
                  </ul>
                  <p className="small text-muted mb-0">
                    Some rights vary by region. Contact us if you need help exercising your rights.
                  </p>
                </section>

                <section id="cookies" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">9. Cookies & Similar Technologies</h2>
                  <p>
                    We use cookies/local storage for authentication, preferences, analytics, and
                    performance. You can control cookies via your browser settings; disabling some
                    cookies may affect functionality.
                  </p>
                </section>

                <section id="third-parties" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">10. Third‑Party Services</h2>
                  <p>
                    The Service may link to or integrate with third‑party sites or services. Their
                    privacy practices are governed by their own policies.
                  </p>
                </section>

                <section id="children" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">11. Children’s Privacy</h2>
                  <p>
                    The Service is not directed to children under 13. We do not knowingly collect
                    personal information from children. If you believe a child provided data, contact
                    us so we can delete it.
                  </p>
                </section>

                <section id="international" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">12. International Transfers</h2>
                  <p>
                    Your information may be processed in countries other than your own. Where
                    required, we implement safeguards to protect your data consistent with this
                    policy and applicable laws.
                  </p>
                </section>

                <section id="changes" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">13. Changes to This Policy</h2>
                  <p>
                    We may update this policy to reflect changes to the Service or legal
                    requirements. We will post updates here and revise the “Last updated” date above.
                    Continued use after changes means you accept the updated policy.
                  </p>
                </section>

                <section id="contact" className="pt-4 mt-2">
                  <h2 className="h5 fw-semibold mb-3">14. Contact Us</h2>
                  <address className="mb-0">
                    <p className="mb-1">
                      <strong>Email: </strong>
                      <a className="link-primary" href="mailto:privacy@pocketpenny.tekimart.com">
                        privacy@pocketpenny.tekimart.com
                      </a>
                    </p>
                  </address>
                </section>

                <div className="d-flex mt-4">
                  <a href="#top" className="ms-auto small link-secondary text-decoration-none">
                    Back to top ↑
                  </a>
                </div>
              </div>
            </div>
          </div>

          {/* Side panel */}
          <aside className="col-12 col-lg-4">
            <div className="card border-0 shadow-sm">
              <div className="card-body p-4">
                <h3 className="h6 fw-semibold mb-3">At a glance</h3>
                <ul className="list-unstyled small mb-3">
                  <li className="mb-1">• You control what you import and can delete it anytime.</li>
                  <li className="mb-1">• We don’t sell your personal information.</li>
                  <li className="mb-1">• Security measures help protect your data.</li>
                </ul>
                <div className="border rounded p-3">
                  <div className="text-muted small mb-1">Questions?</div>
                  <a className="btn btn-outline-primary btn-sm" href="mailto:privacy@pocketpenny.tekimart.com">
                    Contact privacy support
                  </a>
                </div>
              </div>
            </div>
          </aside>
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}
